In [1]:
catalog.list()

[
    'application_record',
    'credit_record',
    'merged_record',
    'model',
    'metrics',
    'parameters',
    'params:train_fraction',
    'params:random_state',
    'params:target_column',
    'params:n_estimators',
    'params:max_features',
    'params:max_depth',
    'params:min_samples_split',
    'params:min_samples_leaf'
]

In [4]:
catalog.load("merged_record")

[02/01/23 00:49:28] INFO     Loading data from 'merged_record' (ParquetDataSet)...              ]8;id=325836;file:///Users/robertcinca/.local/share/virtualenvs/template-analytics-x4ftvWbN/lib/python3.9/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=615756;file:///Users/robertcinca/.local/share/virtualenvs/template-analytics-x4ftvWbN/lib/python3.9/site-packages/kedro/io/data_catalog.py#343\343]8;;\

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,MONTHS_BALANCE,STATUS
0,0,1,1,1,0,577,4,1,0,4,2002,4963,0,1,0,0,0,4,60,7
1,0,1,1,1,0,577,4,1,0,4,2002,4963,0,1,0,0,0,4,0,0
2,0,1,1,1,0,577,4,1,0,4,2002,4963,0,1,0,0,0,4,11,0
3,0,1,1,1,0,577,4,1,0,4,2002,4963,0,1,0,0,0,4,22,0
4,1,1,1,1,0,577,4,1,0,4,2002,4963,0,1,0,0,0,4,60,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,45798,0,0,1,1,415,4,1,3,1,7347,2851,0,0,1,1,11,6,33,0
1048571,45798,0,0,1,1,415,4,1,3,1,7347,2851,0,0,1,1,11,6,44,0
1048572,45798,0,0,1,1,415,4,1,3,1,7347,2851,0,0,1,1,11,6,55,0
1048573,45798,0,0,1,1,415,4,1,3,1,7347,2851,0,0,1,1,11,6,57,0
1048574,45798,0,0,1,1,415,4,1,3,1,7347,2851,0,0,1,1,11,6,58,0